### ISSUE TITLE
Tree visualizer breaks by ORing predicates

### ISSUE THREAD

**Issue by bbonf** [UUDigitalHumanitieslab/gretel-django#52]
e.g. ```//node[@rel="det" or @rel="hd"]```

This also applies to the current version of gretel, but I've noticed it in the context of MWE queries where or-ing is going to be very common.

For more context:
The relevant code is in https://github.com/UUDigitalHumanitieslab/lassy-xpath/blob/develop/projects/lassy-xpath/src/lib/services/extractinator.ts and the problem is that the jQuery's xml parser doesn't like duplicate attributes.

But to solve this, we also need to think about what would make sense from a visual perspective.

**Comment by bbonf** [comment]
To further clarify: this is a minor issue in the parse step for example-based queries or xpath queries. But the bigger problem is that it breaks the analysis step completely.

I'm thinking there should be two steps to the fix:
1. Prevent the Analysis step from breaking when the tree rendering breaks
2. Fix the code in lassy-xpath

**Comment by oktaal** [comment]
Fixed in https://github.com/UUDigitalHumanitieslab/gretel/commit/6909423dc876078380d27c02990700a97de995c9 Analysis step did not break, dragging from the tree didn't work because there is no tree. But it was still possible to drag from the xpath. I changed the style to make this a bit more clear.

**Comment by oktaal** [comment]
Closed by c588facfa1efd342075125433ae01e4b9918f3cb
